add_newline = true
command_timeout = 10000 # 10 seconds

[character]
success_symbol = "ğŸ‘» [âœ](bold purple)"
error_symbol = "ğŸ˜¿ [âœ](bold red)"

# Here is how you can shorten some long paths by text replacement
[directory.substitutions]
"Documents" = "ğŸ“„ "
"Downloads" = "ğŸ“¦ "
"Music" = "ğŸµ "
"Pictures" = "ğŸ–¼ï¸ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ğŸ“„! "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
"Important ğŸ“„ " = " ğŸ“„! "

[aws]
symbol = "â˜ï¸  "

[c]
symbol = "ğ’„ "

[dart]
symbol = "ğŸ¯ "

[directory]
read_only = " ğŸ“‚ğŸ‘€"

[elixir]
symbol = "ğŸ©¸ "

[git_branch]
symbol = "ğŸ‹ "

[golang]
symbol = "ğŸï¸ "

[hg_branch]
symbol = "ğŸ‹ "

[java]
symbol = "â˜•ï¸ "

[memory_usage]
symbol = "ğŸ’¾ "

[nodejs]
symbol = "â¬¡ "

[package]
symbol = "ğŸ“¦ "

[python]
symbol = "ğŸ "

[rust]
symbol = "âš™ï¸ "
